package.json, tsconfig.json, yarn.lock
includes update to acorn parser
=> chore: update yarn lockfile

package.json
=> fix: marketplace "repository" link is broken

.changeset/stale-kiwis-design.md, README.md
=> docs: change to use transferred publisher

.github/workflows/pkg-size.yml
=> ci: use `pull_request_target` event instead

README.md
=> docs: add Open VSX badges

.github/workflows/ci.yml, .github/workflows/pkg-size.yml, .github/workflows/version.yml
This doesn’t work without a lockfile.
=> Remove workflow cache keys

package.json
This aligns the repository with the rest of the unified ecosystem.
=> chore: widen semver dependency ranges

.changeset/config.json, .github/workflows/version.yml, README.md
=> Refactor to rename `master` to `main`

fixtures/fixtures.code-workspace
This is convenient for debugging.
=> Enable language server in fixtures workspace

.changeset/resolve-unreferenced-definitions.md, packages/language-server/lib/convert.js, packages/language-server/lib/documents.js, packages/language-server/lib/language-service-manager.js, packages/language-server/tests/definitions.test.js, packages/language-server/tests/diagnostics.test.js
=> Resolve definitions referencing unopened files

.github/workflows/demo.yml
This doesn’t close the issue, because we still need to configure a domain name.
Refs #261
=> Publish the demo to GitHub pages

.changeset/config.json, .github/workflows/version.yml, README.md, demo/README.md, package.json, packages/language-server/package.json, packages/language-service/package.json, packages/monaco/README.md, packages/monaco/package.json, packages/vscode-mdx/CHANGELOG.md, packages/vscode-mdx/README.md, packages/vscode-mdx/package.json
=> Rename repo to `mdx-analyzer`

.changeset/flat-eagles-add.md, packages/vscode-mdx/syntaxes/source.mdx.tmLanguage
=> Update MDX grammar for VSCode

.changeset/gorgeous-islands-camp.md, packages/language-server/package.json, packages/language-service/lib/language-module.js, packages/language-service/package.json
This is mostly backwards compatible with MDX 2.
=> Update to MDX 3

packages/language-server/package.json, packages/language-service/lib/language-module.js, packages/language-service/package.json, packages/vscode-mdx/package.json, packages/vscode-mdx/src/extension.js, pnpm-workspace.yaml
An easy win, update Volar to get a few bug fixes and improves. ;) (Mainly https://github.com/volarjs/volar.js/pull/77)
=> Update Volar dependencies

fixtures/fixtures.code-workspace, packages/vscode-mdx/README.md, packages/vscode-mdx/package.json, packages/vscode-mdx/src/extension.js
=> Respond to configuration changes to enable/disable the language server

.changeset/ts-version-status-item.md, packages/vscode-mdx/package.json, packages/vscode-mdx/src/extension.js
Clicking it opens a menu to select the TypeScript version to use.
=> Add a TypeScript version status item

packages/language-server/README.md
*   [ ] If applicable, I’ve added docs and tests
Just a fix for this documentation header
=> Fix the README title in the `language-server` package

packages/language-server/index.js, packages/language-server/test/completion.test.js, packages/language-service/lib/language-plugin.js, packages/language-service/lib/virtual-file.js, packages/language-service/test/language-module.js
This way we don’t have to depend on patching TypeScript compiler options.
=> Inject JSX comments into MDX

.changeset/large-dolls-obey.md, package.json, packages/language-service/lib/virtual-code.js, packages/language-service/test/language-module.js
=> Support injected components inside MDX expressions

packages/language-server/index.js, packages/language-server/package.json, packages/language-server/test/completion.test.js, packages/language-server/test/definitions.test.js, packages/language-server/test/diagnostics.test.js, packages/language-server/test/document-link.test.js, packages/language-server/test/document-symbols.test.js, packages/language-server/test/folding-ranges.test.js, packages/language-server/test/hover.test.js, packages/language-server/test/initialize.test.js, packages/language-server/test/no-tsconfig.test.js, packages/language-server/test/prepare-rename.test.js, packages/language-server/test/rename.test.js, packages/language-service/lib/virtual-code.js, packages/language-service/package.json, packages/language-service/test/language-module.js, packages/vscode-mdx/package.json
=> Update to Volar 2.1

.changeset/smooth-terms-build.md, README.md, contributing.md, fixtures/fixtures.code-workspace, package.json, packages/language-server/README.md, packages/language-service/README.md, packages/language-service/lib/language-plugin.js, packages/language-service/lib/service-plugin.js, packages/language-service/lib/tsconfig.js, packages/language-service/package.json, packages/vscode-mdx/README.md, packages/vscode-mdx/package.json
This adds a lot of missing documentation, and removes some that has become obsolete.
=> Update the documentation

.github/workflows/main.yml, package.json
Enable code coverage and use codecov to display it.
=> Enable code coverage

.changeset/tiny-vans-protect.md, fixtures/debug/example.mdx, fixtures/debug/loader.mjs, fixtures/debug/run.mjs, fixtures/fixtures.code-workspace, package.json, packages/vscode-mdx/package.json
MDX files are compiled to JavaScript and support source maps. They can be debugged.
=> Add support for breakpoints

.changeset/dry-pumas-begin.md, CONTRIBUTING.md, README.md, package.json, packages/language-server/README.md, packages/language-server/index.js, packages/language-server/package.json, packages/language-service/README.md, packages/typescript-plugin/index.cjs, packages/typescript-plugin/package.json, packages/vscode-mdx/README.md, packages/vscode-mdx/package.json
This updates `load-plugin` as well as dependencies related to markdown linting to the latest version.
=> Update dependencies related to unified

.changeset/red-timers-love.md, packages/language-server/index.js, packages/language-server/package.json, packages/language-server/test/completion.test.js, packages/language-server/test/diagnostics.test.js, packages/language-server/test/document-link.test.js, packages/language-server/test/initialize.test.js, packages/language-service/lib/commands.js, packages/language-service/lib/language-plugin.js, packages/language-service/lib/service-plugin.js, packages/language-service/package.json, packages/language-service/test/language-module.js, packages/typescript-plugin/package.json, packages/vscode-mdx/package.json
Upgrade to Volar 2.2. 💪
Closes #427
=> Upgrade to Volar 2.2

.changeset/spicy-tables-crash.md, packages/language-server/package.json
This adds support for markdown hover info, such as image previews.
Closes #436
=> Update to Volar services 0.0.45

.changeset/slimy-insects-hide.md, packages/vscode-mdx/syntaxes/source.mdx.tmLanguage
=> Update the MDX grammar

.changeset/five-bobcats-bow.md, packages/vscode-mdx/syntaxes/source.mdx.tmLanguage
The grammar was updated to the latest version of https://github.com/wooorm/markdown-tm-language
Closes #472
=> Update the MDX grammar from upstream

.changeset/gold-meals-bathe.md, packages/language-server/test/syntax-toggle.test.js, packages/language-service/lib/service-plugin.js
This is supported by more markdown flavours.
=> Use two tildes to toggle delete syntax

CONTRIBUTING.md
Remove the reference. I don’t think an alternative link is needed. The actual text is enough
=> Remove reference to twitter
