mdx-js/mdx-analyzer

- README.md
I installed version 0.2.2 of this extension, alongside VSCode ESLint 2.1.14 on VSCode 1.53.2.  I have eslint 7.20.0 and eslint-plugin-mdx 1.8.2.  Running eslint from the command line reported violations as expected.  However, VSCode refused to show squiggly red lines under eslint violations in an `.mdx` file until I added this "eslint.validate" config in addition to the above suggested config.
The array elements preceding "mdx" are the default values - without them you'll break validation elsewhere
> docs: document seemingly necessary eslint.validate config

- .changeset/sixty-geckos-design.md
- .eslintrc
- .remarkrc
- README.md
- package.json
- yarn.lock
Mentioning _VSCode_ in the display name and description is redundant, as it’s used for representing the extension inside VSCode (or even an alternative compatible editor that isn’t VSCode).
The `qna` link is linked from https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx&ssr=false#qna. By default it appears to link the repository issue tracker.
The sponsor url is rendered in VSCode. For example:
The `funding` field is for npm packages and is actually meaningless for VSCode extensions. I don’t know what the `donate` field is used for, but it seems redundant too.
> chore: update extension metadata content and README

- .changeset/great-owls-sip.md
- package.json
Addresses issue #203. I believe that `embeddedLanguages` should not contain `"text.html.markdown": "markdown"`; see my response to the issue at https://github.com/mdx-js/vscode-mdx/issues/203#issuecomment-1221812813
> fix: remove superfluous `embeddedLanguages` setting

- .changeset/short-coins-bow.md
- syntaxes/mdx.tmLanguage.json
- test/fixture.mdx
In JSX, you can include JS expressions within tags, like:
```
{doSomething(‘a’, 7)}
```
This PR adds syntax highlighting for those expressions.
It will still highlight JS that isn’t valid to include in a JSX evaluated expression (eg. a class definition), which as far as I can tell is a limitation of how embedded languages work in TextMate syntax highlighting definitions.
> feat: support for highlighting JSX evaluated expressions

- .npmrc
Previously this was needed due to some problematic dependencies. We no longer have those dependencies.
> chore: remove legacy-peer-deps from .npmrc

- .changeset/ignore-non-mdx-files.md
- fixtures/node16/component.tsx
- packages/language-server/index.js
- packages/language-server/lib/documents.js
- packages/language-server/tests/definitions.test.js
- packages/language-server/tests/document-symbols.test.js
- packages/language-server/tests/hover.test.js
- packages/language-server/tests/prepare-rename.test.js
- packages/language-server/tests/rename.test.js
- packages/language-service/index.js
- packages/language-service/lib/index.js
- packages/vscode-mdx/package.json
Previously the MDX language server handled TypeScript IntelliSense for JavaScript and TypeScript files as well. This led to duplicate IntelliSense results in the editor if people have also enabled TypeScript IntelliSense.
These files are still synchronized with the MDX language server, because they are needed for context, but they no longer yield results when interacted with.
This also adds tests for when a document does not exist.
Closes #270
> Ignore non MDX files when processing

- .vscode/launch.json
- packages/vscode-mdx/language-configuration.json
- packages/vscode-mdx/package.json
I just find comments in JSON weird.
Also VSCode has builtin file support for files names `language-configuration.json`, but not for `language-configuration.jsonc`.
> Remove comments from JSON files

- .github/workflows/main.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/version.yml
The `name` property is used for GitHub actions output, but in my opinion the command run often describes it better than a given name.
> Remove names and excessive whitespace from workflows

- .vscode/launch.json
- packages/vscode-mdx/src/extension.js
This setup also handles automatic re-attaching if the debugged VSCode window is reloaded.
> Simplify debug configuration

- .changeset/remark-syntax-plugins.md
- fixtures/frontmatter/frontmatter.mdx
- fixtures/frontmatter/tsconfig.json
- packages/language-server/README.md
- packages/language-server/index.js
- packages/language-server/lib/configuration.js
- packages/language-server/lib/language-service-manager.js
- packages/language-server/package.json
- packages/language-server/tests/plugins.test.js
- packages/language-server/tests/utils.js
- packages/vscode-mdx/README.md
- packages/vscode-mdx/package.json
- packages/vscode-mdx/tsconfig.schema.json
Syntax plugins can be added by adding an `mdx` section in your `tsconfig.json` file. This is then parsed following the same format as `unified-engine` [configuration][].
For example, to support [frontmatter][] and [GFM][], add the following section to `tsconfig.json`:
```jsonc
{
"compilerOptions": {
// …
},
"mdx": {
"plugins": [
"remark-frontmatter",
"remark-gfm"
]
}
}
```
This also adds the JSON schema for the new field in `tsconfig.json`.
Closes #266
> Support remark plugins in the language server

- .changeset/allowjs-crash.md
- fixtures/demo/tsconfig.json
- fixtures/frontmatter/tsconfig.json
- fixtures/node16/tsconfig.json
- packages/language-server/lib/language-service-manager.js
> Fix crash of `allowJs` and `checkJs` are missing

- .changeset/fix-crash.md
- fixtures/fixtures.code-workspace
- fixtures/no-tsconfig/readme.mdx
- packages/language-server/lib/configuration.js
- packages/language-server/lib/language-service-manager.js
- packages/language-server/tests/no-tsconfig.test.js
- packages/language-server/tests/plugins.test.js
This affects:
- If no `tsconfig.json` exists.
- If `tsconfig.json` specifies `includes`, but doesn’t include the MDX file.
- If `tsconfig.json` specifies `excludes` and excludes the MDX file.
- If a new file is created.
- If a file is renamed.
Closes #269
> Fix crash if file is not in the TypeScript project

- .changeset/fix-folding-ranges.md
- fixtures/node16/mixed.mdx
- packages/language-server/index.js
- packages/language-server/lib/convert.js
- packages/language-server/tests/document-symbols.test.js
- packages/language-server/tests/folding-ranges.test.js
- packages/language-service/lib/outline.js
Some cases caused a crash when requesting folding ranges related to markdown headings. This is fixed now.
This also adds support for folding range categories.
Also tests have been added for folding ranges.
Closes #289
> Fix error when requesting folding ranges

- packages/language-server/tests/utils.js
This means the timeout to perform a cleanup is no longer necessary.
> The test runner now calls beforeEach after test failures

- demo/package.json
- demo/src/index.js
- demo/src/mdx.worker.js
- demo/tsconfig.json
- packages/monaco/README.md
- packages/monaco/mdx.worker.js
- packages/monaco/package.json
> Support remark plugins in Monaco and demo

- .changeset/handle-shadow-positions.md
- fixtures/node16/undefined-props.mdx
- packages/language-server/tests/definitions.test.js
- packages/language-server/tests/folding-ranges.test.js
- packages/language-server/tests/prepare-rename.test.js
- packages/language-server/tests/rename.test.js
- packages/language-service/lib/index.js
- packages/language-service/lib/utils.js
MDX content is converted to JavaScript. TypeScript then uses this JavaScript handle requests. It then returns positional information that needs to be mapped back to the original MDX content.
This was previously not handled properly, leading to mostly false positive results. This is now handled better by stripping results that reference locations that can’t be mapped back to the original MDX content.
This was mostly tested manually. More tests are needed.
> Fix various bugs related to shadow positions

- .changeset/filter-completion.md
- fixtures/node16/completion.mdx
- packages/language-server/tests/completion.test.js
- packages/language-service/lib/index.js
- packages/language-service/lib/utils.js
TypeScript based completion is only relevant inside JavaScript based parts, such as ESM and JSX. It’s irrelevant and distracting when writing markdown sections.
This also adds missing tests for completion.
> Skip completion in markdown content

- .changeset/typescript-5.md
- package.json
- packages/language-server/package.json
- packages/language-service/lib/index.js
Also the missing `typescript` dependency was added to `@mdx-js/language-server`.
> Update to TypeScript 5

- packages/language-service/lib/index.js
- packages/language-service/lib/object.js
These type errors were caused by TypeScript updates.
> Fix type errors

- package.json
`@types/hast` depends on `@types/unist@*`. This causes TypeScript compatibility issues.
> Pin @types/unist to version 2

- packages/vscode-mdx/package.json
This changes the color of the banner on https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx, so it stands out a bit more.
Default:
With this change:
> Define the gallery banner color

- packages/vscode-mdx/package.json
- packages/vscode-mdx/script/build.mjs
VSCode related packages are improperly dual published. By resolving to ESM instead of CJS, we can slightly reduce bundle size.
More importantly, the upcoming transition to Volar will add additional features, some of which rely on dependencies that don’t even work without a custom ESBuild plugin.
I’m pushing this change ahead of the transition to Volar, to reduce the diffs in that upcoming PR.
> Use JavaScript build script

- .changeset/lucky-books-tan.md
- packages/vscode-mdx/package.json
- packages/vscode-mdx/src/document-drop-edit-provider.js
- packages/vscode-mdx/src/extension.js
- packages/vscode-mdx/tsconfig.json
When dropping an image, the image is downloaded next to the file, and a markdown link is generated. When text is dropped, the text is inserted as-is. This only works in VS Code.
This uses a naive text-based approach. This is very similar to the implementation for markdown files that’s builtin to VS Code.
Closes #322
> Support to drag and drop images and text into MDX

- packages/vscode-mdx/src/extension.js
As an example, volarjs/starter enables client pull diagnostics by default, which causes vscode to send a diagnostic request to the server when the current file changes, which is invalid for project-aware diagnostics. Specifically, vscode does not re-request .mdx diagnostics when a .ts file is changed that affects the .mdx type.
Remove `diagnosticModel: DiagnosticModel.Pull` to solve the problem, since the default behavior is server push instead of client pull.
> fix: Push diagnostics from server

- .changeset/tender-rice-notice.md
- packages/vscode-mdx/package.json
- packages/vscode-mdx/syntaxes/mdx.markdown.tmLanguage.json
This is based on https://github.com/tamasfe/taplo.
> Syntax highlight MDX code blocks in markdown files

- packages/vscode-mdx/src/document-drop-edit-provider.js
A mime type of `uri-list` is for example files dragged from the VSCode tree view.
Images are turnes into Markdown images. These are detected based on a hardcoded list of file extensions. Other URIs are inserted as-is.
If the dragged URI uses the same scheme as the document it was dragged in, a relative path is inserted. Otherwise the full URI is used.
Closes #322
> Handle dragging uri-list into MDX files

- .changeset/fix-drop-provider.md
- packages/vscode-mdx/src/document-drop-edit-provider.js
This was using `URL.canParse`, which isn’t available in the Node.js version used by VSCode. This failed silently. This is fixed by using strict parse mode from `vscode-uri`.
Closes #322
> Fix dropping local media in an MDX file

- .changeset/tasty-geckos-obey.md
- packages/language-service/lib/language-module.js
- packages/language-service/test/language-module.js
Formatting embedded content causes too much unexpected behaviour in MDX files.
Closes #355
> Disable formatting

- .changeset/tame-moles-type.md
- packages/language-server/test/diagnostics.test.js
- packages/language-service/lib/language-module.js
- packages/language-service/test/language-module.js
If the Props type isn’t defined, it now falls back to an empty shape instead of any. Also all keys are marked as readonly. As a result, props are no longer represented using the string `Props`, but an inline representation of the shape of the props.
Given that the upcoming support for an MDX layout also requires a patched version of `Props`, this new setup is more consistent.
Also the `props` description now contains a link to the props page on the MDX website.
> Enhance how the Props type is used

- .changeset/purple-mice-rhyme.md
- package.json
- packages/language-service/lib/language-module.js
- packages/language-service/test/language-module.js
- packages/language-service/types.d.ts
> Support MDX layout

- packages/language-service/lib/language-module.js
- packages/language-service/test/language-module.js
MDX allows to use indentation. In regular markdown however, indented code represents a code block. To work around this, all virtual markdown chunks are now dedented. This may change the semantic meaning of certain markdown, but it doesn’t affect editor features as far as I’m aware.
> Dedent virtual markdown chunks

- .changeset/purple-kings-unite.md
- packages/language-server/lib/language-server-plugin.js
- packages/language-service/lib/language-module.js
- packages/language-service/test/language-module.js
TypeScript isn’t needed to parse MDX into virtual files. The removal of this dependency, means that the language module could later be used in places where TypeScript is unavailable.
> Remove the language module dependency on TypeScript

- .changeset/pink-beans-move.md
- packages/language-service/lib/virtual-file.js
- packages/language-service/test/language-module.js
This means that if the component is used in another file, the return type of MDXContent is inferred as JSX.Element, not void.
> Fix return type of MDXContent in case of syntax error

- packages/vscode-mdx/README.md
> docs: update some outdated links

- .changeset/rare-cycles-shave.md
- .changeset/real-eels-dance.md
- packages/language-server/index.js
- packages/language-service/index.js
- packages/language-service/lib/commands.js
- packages/language-service/lib/mdast-utils.js
- packages/language-service/lib/service-plugin.js
- packages/language-service/lib/virtual-file.js
- packages/language-service/package.json
- packages/vscode-mdx/package.json
- packages/vscode-mdx/src/extension.js
The prose syntax is based on the current text selection and the AST. If the selection is within range of the syntax that’s toggled, the syntax is removed. Otherwise the selected text is expanded to include full words and wrapped.
The supported syntaxes are:
| mdast node | LSP command | VSCode command | Keyboard shortcut | macOS shortcut |
| --- | --- | --- | --- | --- |
| `delete` | `mdx/toggleDelete` | `mdx.toggleDelete`  | <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>5</kbd> | <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd>
| `emphasis` …
> Create commands to toggle prose syntax

- packages/language-server/package.json
- packages/language-server/test/document-link.test.js
- packages/language-server/test/utils.js
This replaces the use of `URL` with `vscode-uri`. This handles Windows paths better than the combination of both.
> Fix the language server tests on Windows

- .changeset/four-cats-scream.md
- packages/language-server/index.js
- packages/language-service/lib/language-plugin.js
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-module.js
- packages/vscode-mdx/tsconfig.schema.json
The MDX language service now accepts the option `checkMdx`. When this is enabled, it tells TypeScript to type check the virtual JSX by inserting a `@ts-check` comment. The language server reads this as the option `mdx.checkMdx` from `tsconfig.json`.
Closes #352
> Support strict type checking in MDX

- .changeset/unlucky-tools-kiss.md
- packages/language-server/test/completion.test.js
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-module.js
Organizing imports sometimes duplicates them. This fixes that by including a trailing newline right after the ESM nodes in the virtual code ranges.
> Avoid duplication when organizing imports

- .changeset/mean-avocados-accept.md
- packages/vscode-mdx/language-configuration.json
Block comments were auto closed twice, which leads to invalid MDX. Now it’s auto closed only once.
> Fix duplicate comment auto closing

- .changeset/large-dolls-obey.md
- packages/language-server/test/diagnostics.test.js
- packages/language-service/lib/jsx-utils.js
- packages/language-service/lib/virtual-code.js
- packages/language-service/package.json
- packages/language-service/test/language-module.js
This defines the `_components` variable in `_createMdxContent`. This variable contains all components injected through the `components` prop, a reference to `props`, and all local variables. All MDX JSX tags are prefixed with `_components.` in the virtual code.
As a result, components declared in the `components` prop are allowed. Components from both the `components` prop and local variables are displayed in the autocomplete.
A downside of this approach is that documentation is lost for local components. To mitigate this, only unknown …
> Add minimal support for the components prop

- .changeset/curvy-cows-matter.md
- README.md
- packages/tsconfig.json
- packages/typescript-plugin/CHANGELOG.md
- packages/typescript-plugin/LICENSE
- packages/typescript-plugin/README.md
- packages/typescript-plugin/index.cjs
- packages/typescript-plugin/package.json
- packages/typescript-plugin/tsconfig.json
- packages/vscode-mdx/package.json
- packages/vscode-mdx/script/build.mjs
This allows editors outside of Visual Studio Code to use the TypeScript plugin as well.
> Publish the TypeScript plugin as an npm package

- .changeset/fuzzy-poets-wonder.md
- packages/language-server/index.js
- packages/language-server/package.json
- packages/language-server/test/initialize.test.js
Since mdx-analyzer is now integrated with tsserver, the language server no longer requires complete TS language features. Using `volar-service-typescript/lib/plugins/syntactic.js` instead of the completed service plugin can avoid the language server registering unnecessary trigger characters.
Initialize Result before PR:
```json
"signatureHelpProvider": {
"triggerCharacters": [
"(",
",",
"<"
],
"retriggerCharacters": [
")"
]
},
"completionProvider": {
"triggerCharacters": [
".",
"\"",
"'",
"`",
"/",
"<",
"@",
"#",
" ",
"*",
"-",
":", …
```
> Using syntax-only TS service plugin

- .changeset/purple-tomatoes-drop.md
- packages/language-service/lib/commands.js
Without this fix, the syntax toggles didn’t do anything at all.
> Fix the file lookup in syntax toggles

- .changeset/silver-boats-kneel.md
- packages/vscode-mdx/package.json
VSCode does this for markdown files too. Some validation results are not wanted. Some are even false positives.
Closes #424
> Disable markdown based linting by default

- .changeset/hot-lies-wink.md
- packages/language-server/index.js
If TypeScript isn’t enabled in the language server, there’s no need to watch file extension other than `mdx`.
> Only watch TS related file extensions if needed

- .changeset/eighty-masks-matter.md
- packages/language-server/index.js
We need the config file name provided by `createTypeScriptProjectProvider()` in order to resolve options from `tsconfig.json`.
> Fix resolving MDX options from tsconfig.json

- .changeset/khaki-coats-press.md
- packages/vscode-mdx/README.md
MDX syntax highlighting can’t possibly support all past, present, and future languages in code blocks. Extensions can inject their own syntax highlighting.
This documentation helps extension authors to support their own language in MDX code blocks.
> Document syntax highlighting for MDX code blocks

- .changeset/cold-turtles-divide.md
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-plugin.js
This solution solves an upstream regression and is backwards compatible for our use case.
Refs https://github.com/microsoft/TypeScript/issues/58960
> Fix compatibility with TypeScript 5.5

- .changeset/large-shoes-applaud.md
- packages/language-server/README.md
- packages/language-server/index.js
- packages/language-server/package.json
- packages/language-server/test/initialize.test.js
- packages/language-server/test/syntax-toggle.test.js
- packages/language-service/README.md
- packages/language-service/index.js
- packages/language-service/lib/commands.js
- packages/language-service/lib/service-plugin.js
- packages/vscode-mdx/package.json
- packages/vscode-mdx/src/extension.js
- tsconfig.base.json
LSP commands are the intended way to implement custom behaviour.
> Change custom request types to LSP commands

- .changeset/empty-donkeys-notice.md
- packages/language-server/test/syntax-toggle.test.js
- packages/language-service/lib/service-plugin.js
This matches `remark-stringify` defaults.
> Use an asterisk to toggle emphasis

- .changeset/sweet-rabbits-lick.md
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-plugin.js
Virtual code generation from estree expressions was based on an assumption of the order in which JSXIdentifier nodes are visited. `estree-walker` visits the nodes in property order. The parser generates AST properties in an order that broke our code generation. As a result, the string `_components.` was injected in an incorrect position in the virtual code, yielding syntax errors.
This is now resolved by explicitly handling `JSXElement` nodes in both the enter and leave methods, instead of just handling `JSXIdentifier` nodes.
Closes #485
> Explicitly handle JSX tags in order

- .changeset/olive-tips-appear.md
- packages/language-server/test/completion.test.js
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-plugin.js
This change adds support for auto-imports.
The virtual code now contains an empty import of the JSX runtime. This import was chosen, because it must exist anyway. This is immediately followed by an empty code mapping, meaning TypeScript always has a place to insert auto-imports.
Since JSX components can be injected, they are sometimes prefixed with `_components.` in the virtual code. To support auto-import completions, an additional mapping is now made to an expression containing merely the identifier. As a result, the editor now shows auto-import completions, unless `MDXProvidedComponents` is defined. I don’t know why the existence of `MDXProvidedComponents` matters, but this probably matches the expectation of users anyway.
The auto-imports will not be followed by a blank line. This can …
> Fix auto-imports

- .changeset/legal-crews-visit.md
- packages/language-server/README.md
- packages/language-service/README.md
- packages/typescript-plugin/README.md
- packages/typescript-plugin/lib/index.cjs
- tsconfig.base.json
The asynchronous TypeScript plugin keeps causing issues. The goal is to move away from that and make it synchronous. Node.js 20.19 adds support for `require(esm)`, which is a great first step for our use case.
VSCode currently ships with Node.js 20.18. However, this is still fine, as dependencies are bundled in the VSCode extension.
> Drop support for Node.js 18

- .changeset/eighty-cats-glow.md
- .changeset/petite-keys-count.md
- .changeset/social-items-cut.md
- packages/language-server/lib/index.js
- packages/language-server/package.json
- packages/language-service/lib/tsconfig.js
- packages/typescript-plugin/lib/index.cjs
- packages/typescript-plugin/package.json
TypeScript plugins only support a synchronous API. Volar has a way to support asynchronous plugins, but it’s hacky and keeps breaking. This change makes the loading of remark plugins synchronous, allowing us to make the TypeScript plugin synchronous as well.
For now jiti is used to load plugins synchronously. As soon as VSCode ships with a Node.js version that supports `require(esm)`, we can replace jiti with `createRequire()`.
`load-plugin` has some additional features which are now not implemented. They were also not documented as part of MDX analyzer. I think these are edge cases. They can be reconsidered when users ask for them.
See https://github.com/volarjs/volar.js/issues/262
> Resolve remark plugins synchronously

- .changeset/silly-loops-wait.md
- fixtures/node16/organize-imports.mdx
- package.json
- packages/language-server/test/code-action.test.js
- packages/language-service/lib/virtual-code.js
- packages/language-service/test/language-plugin.js
The organize imports command broke documents where imports are present. This was a regression caused by the logic to support auto imports.
Closes #502
> Fix organizing imports

- .changeset/flat-bottles-carry.md
- packages/typescript-plugin/lib/index.cjs
If a TypeScript project doesn’t include any files, this is reported on `tsconfig.json`. However, it’s useful to have a `tsconfig.json` file to configure TypeScript inside MDX. This diagnostic is now filtered if there are MDX files in the project.
> Filter diagnostics if only MDX files are found
